[2024-09-18T17:34:40.535-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-18T17:34:40.541-0500] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.fetch_data manual__2024-09-18T22:34:36.875430+00:00 [queued]>
[2024-09-18T17:34:40.544-0500] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.fetch_data manual__2024-09-18T22:34:36.875430+00:00 [queued]>
[2024-09-18T17:34:40.544-0500] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-18T17:34:40.550-0500] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-09-18 22:34:36.875430+00:00
[2024-09-18T17:34:40.555-0500] {standard_task_runner.py:72} INFO - Started process 23281 to run task
[2024-09-18T17:34:40.558-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'fetch_data', 'manual__2024-09-18T22:34:36.875430+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/var/folders/48/1hc7518x2bsfgjm34fs7dth00000gn/T/tmptghhl1zh']
[2024-09-18T17:34:40.559-0500] {standard_task_runner.py:105} INFO - Job 32: Subtask fetch_data
[2024-09-18T17:34:40.579-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.fetch_data manual__2024-09-18T22:34:36.875430+00:00 [running]> on host binhs-macbook-pro.local
[2024-09-18T17:34:40.609-0500] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T22:34:36.875430+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-18T22:34:36.875430+00:00'
[2024-09-18T17:34:40.610-0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-18T17:34:40.610-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-18T17:34:40.611-0500] {logging_mixin.py:190} INFO - Current task name:fetch_data state:running start_date:2024-09-18 22:34:40.541664+00:00
[2024-09-18T17:34:40.611-0500] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-09-18T17:34:40.611-0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-18T17:34:40.615-0500] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/binhpham/airflow/dags/etl_pipeline.py", line 15, in fetch_data
    df.to_csv('/sales_data.csv', index=False)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
OSError: [Errno 30] Read-only file system: '/sales_data.csv'
[2024-09-18T17:34:40.651-0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-18T17:34:40.652-0500] {logging_mixin.py:190} INFO - Task start:2024-09-18 22:34:40.541664+00:00 end:2024-09-18 22:34:40.651695+00:00 duration:0.110031
[2024-09-18T17:34:40.652-0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_data> dag:<DAG: etl_pipeline> dagrun:<DagRun etl_pipeline @ 2024-09-18 22:34:36.875430+00:00: manual__2024-09-18T22:34:36.875430+00:00, state:running, queued_at: 2024-09-18 22:34:36.887233+00:00. externally triggered: True>
[2024-09-18T17:34:40.652-0500] {logging_mixin.py:190} INFO - Failure caused by [Errno 30] Read-only file system: '/sales_data.csv'
[2024-09-18T17:34:40.653-0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=fetch_data, run_id=manual__2024-09-18T22:34:36.875430+00:00, execution_date=20240918T223436, start_date=20240918T223440, end_date=20240918T223440
[2024-09-18T17:34:40.657-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-18T17:34:40.658-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task fetch_data ([Errno 30] Read-only file system: '/sales_data.csv'; 23281)
Traceback (most recent call last):
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/binhpham/airflow/dags/etl_pipeline.py", line 15, in fetch_data
    df.to_csv('/sales_data.csv', index=False)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/Users/binhpham/Projects/dbt_project/venv/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
OSError: [Errno 30] Read-only file system: '/sales_data.csv'
[2024-09-18T17:34:40.705-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-18T17:34:40.715-0500] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-18T17:34:40.717-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
